import { palette } from "./palette";

export const darkThemeColors = {
  buttonDisabled: palette.disabledButton,
  buttonDisabledText: palette.white,
  buttonPrimary: palette.primary500,
  buttonPrimaryText: palette.white,
  buttonSecondary: palette.dark3,
  buttonSecondaryText: palette.white,
  checkboxCheck: palette.white,
  checkboxHightLight: palette.primary500,
  chipHighlight: palette.primary500,
  chipText: palette.white,
  inputBlurredBackground: palette.dark2,
  inputFocusedBackground: palette.dark3,
  inputFocusedBorder: palette.greyscale400,
  inputPlaceholderText: palette.greyscale500,
  inputTextColor: palette.white,
  textDefault: palette.white,
  toggleThumb: palette.white,
  toggleTrackFalse: palette.dark2,
  toggleTrackTrue: palette.primary500,
  inActiveRing: palette.greyscale200,
  activeRing: palette.primary500,
  wheelActive: palette.primary500,
  accordionBackground: palette.greyscale900,
  accordionBottomBorder: palette.greyscale800,
  accordionSubtext: palette.primary400,
  screenBackground: palette.dark1,
  navigationBorder: palette.greyscale800,
  navigationPrimary: palette.primary500,
  sliderActive: palette.primary500,
  sliderInactive: palette.greyscale200,
  textLight: palette.greyscale500,
  primary: palette.primary500,
  cardBackground: palette.dark3,
  comboSectionBackground: palette.greyscale900,
  imageBorder: palette.greyscale800,
  translucent: palette.black_50,
  cardText: palette.white,
  cardGradient: palette.greyscale900,
  tabBarActiveTintColor: palette.primary500,
  tabBarInactiveTintColor: palette.greyscale500,
  error: palette.error,
};
