import { palette } from "./palette";

export const lightThemeColors = {
  buttonDisabled: palette.disabledButton,
  buttonDisabledText: palette.white,
  buttonPrimary: palette.primary500,
  buttonPrimaryText: palette.white,
  buttonSecondary: palette.primary100,
  buttonSecondaryText: palette.primary500,
  checkboxCheck: palette.white,
  checkboxHightLight: palette.primary500,
  chipHighlight: palette.primary500,
  chipText: palette.white,
  inputBlurredBackground: palette.greyscale200,
  inputFocusedBackground: palette.greyscale100,
  inputFocusedBorder: palette.greyscale800,
  inputPlaceholderText: palette.greyscale500,
  inputTextColor: palette.greyscale900,
  textDefault: palette.greyscale900,
  toggleThumb: palette.white,
  toggleTrackFalse: palette.greyscale200,
  toggleTrackTrue: palette.primary500,
  inActiveRing: palette.greyscale400,
  activeRing: palette.primary500,
  wheelActive: palette.primary500,
  accordionBackground: palette.greyscale50,
  accordionBottomBorder: palette.greyscale200,
  accordionSubtext: palette.primary400,
  screenBackground: palette.white,
  navigationBorder: palette.greyscale400,
  navigationPrimary: palette.primary500,
  sliderActive: palette.primary500,
  sliderInactive: palette.greyscale200,
  textLight: palette.greyscale700,
  primary: palette.primary500,
  cardBackground: palette.white,
  comboSectionBackground: palette.greyscale100,
  imageBorder: palette.greyscale300,
  translucent: palette.white_50,
  cardText: palette.white,
  cardGradient: palette.greyscale500,
  tabBarActiveTintColor: palette.primary500,
  tabBarInactiveTintColor: palette.greyscale500,
  error: palette.error,
};
